// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
public class ADManager
{
	private static string PUBLISHER_ID = "56OJw6l4uNH8tHA2uR";
	private static string FlexibleInlinePPID = "16TLupZlApr4WNUEj6eJcLbk";
	private static string LOCATION_BOTTOM = "isBottom"; 
	private static AndroidJavaClass jc = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
	private static AndroidJavaObject jo = jc.GetStatic<AndroidJavaObject>("currentActivity");



	public static void AddAD(){
		string[] paramaddFlexibleBannerAd = new string[3];
		//PUBLISHER_ID.must set
		paramaddFlexibleBannerAd[0]=PUBLISHER_ID;
		//FlexibleInlinePPID,must set
		paramaddFlexibleBannerAd[1]=FlexibleInlinePPID;
		//set Advertising display position,default Displayed at the bottom,must set
		paramaddFlexibleBannerAd[2]=LOCATION_BOTTOM;
		jo.Call("addFlexibleBannerAd",paramaddFlexibleBannerAd);

	}


	public static void ShowDomobWall(){



		string[] paramloadOfferWall = new string[2];
		//PublisherID
		paramloadOfferWall[0]="96ZJ2b8QzehB3wTAwQ";
		//userID
		paramloadOfferWall[1]="";
		jo.Call("loadOfferWall",paramloadOfferWall);    
	}

	public static void ShowDomobAD(){

		string[] paramaddInterstitialAd = new string[3];
		//PUBLISHER_ID.must set
		paramaddInterstitialAd[0]="56OJw6l4uNH8tHA2uR";
		//InterstitialPPID,must set
		paramaddInterstitialAd[1]="16TLupZlApr4WNUEhjfYEMwi";
		//set Advertising size,such as,INTERSITIAL_SIZE_300X250,INTERSITIAL_SIZE_600X500...must set
		//		int width =(int)(Screen.width *0.8f);
		//		int height =(int)(width*0.8f);
		paramaddInterstitialAd[2]="300x250";//width+"x"+height;
		jo.Call("addInterstitialAd",paramaddInterstitialAd);
	}

	public static void ShowDownload(){
		string[] paramaddInterstitialAd = new string[1]{"http://shouji.360tpcdn.com/140523/33033157cfa2cc9f70f4bbc744a0abb9/com.royalgame.color2048_1.apk"};
		jo.Call("showDownload",paramaddInterstitialAd);
	}
}


